### ISSUE TITLE
certificate woes

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-reports-floodgauge#4]
```
2018-03-07T08:24:04.595Z - error: FloodgaugeDataSource > poll > fetchResults: Error fetching data, unable to verify the first certificate, Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```

**Comment by matthewberryman** [comment]
I'm wondering if this is something server side or if the https module is braindead and lacking certs (might need something higher level?)

**Comment by matthewberryman** [comment]
The certificate chain presented by the server is missing the intermediate certificate (and node has only access to the ones from the OS = root CAs).

Luckily there's a package for adding the intermediate client side https://www.npmjs.com/package/ssl-root-cas
